name: Deploy FactChain1155 contract
on:
  push:
    branches: [ main ]
    paths:
      - fc-community-contracts/src/FactChain1155.sol
      - fc-community-contracts/src/utils/Ownable.sol
  workflow_dispatch:
jobs:
  deploy-contract:
    runs-on: ubuntu-latest
    env:
      CONTRACT_NAME: FactChainNFT
      CHAIN_ID: 11155111
      ETH_RPC_URL: ${{ secrets.RPC_ETH_SEPOLIA_HTTPS }}
      PRIVATE_KEY: ${{ secrets.DEPLOYER_PK }}
      ETHERSCAN_URL: https://sepolia.etherscan.io
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_SEPOLIA_API_KEY }}
      OWNER_ADDRESS: ${{ vars.OWNER_ADDRESS }}
    permissions: write-all
    defaults:
      run:
        working-directory: ./fc-community-contracts
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Build contract
        run: forge build

      - name: Deploy contract
        id: deploy
        run: |
          createOutput=`forge create "src/${{ env.CONTRACT_NAME }}.sol:${{ env.CONTRACT_NAME }}" --verify --json --rpc-url=$ETH_RPC_URL --private-key=$PRIVATE_KEY --constructor-args $OWNER_ADDRESS https://gateway.pinata.cloud/ipfs/`
          echo "forge create output:\n\n$createOutput"
          deploymentOutput=`echo "${createOutput}" | head -1`
          echo "deploymentOutput=$deploymentOutput" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.CONTRACT_NAME }}.abi.json
          path: ./fc-community-contracts/out/${{ env.CONTRACT_NAME }}.sol/${{ env.CONTRACT_NAME }}.json

      - name: Log detail of deployment
        run: |
          echo "# Contract ${{ env.CONTRACT_NAME }} deployed :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "- Deployer: [${{ fromJson(steps.deploy.outputs.deploymentOutput).deployer }}](${ETHERSCAN_URL}/address/${{ fromJson(steps.deploy.outputs.deploymentOutput).deployer }})" >> $GITHUB_STEP_SUMMARY
          echo "- Deployed to: [${{ fromJson(steps.deploy.outputs.deploymentOutput).deployedTo }}](${ETHERSCAN_URL}/address/${{ fromJson(steps.deploy.outputs.deploymentOutput).deployedTo }})" >> $GITHUB_STEP_SUMMARY
          echo "- Transaction hash: [${{ fromJson(steps.deploy.outputs.deploymentOutput).transactionHash }}](${ETHERSCAN_URL}/tx/${{ fromJson(steps.deploy.outputs.deploymentOutput).transactionHash }})" >> $GITHUB_STEP_SUMMARY
